[build]
  # Build command to inject environment variables
  command = "npm run build"
  # Publish the root directory
  publish = "."

[build.environment]
  # Node.js version (not required for static sites, but good to specify)
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (if needed)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301